name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches:
      - internal-form

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.0'
        cache: 'npm'
    - run: npm run build
    - uses: actions/upload-artifact@v3.1.2
      with:
        path: build/static
