name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches:
      - internal-form

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.0'
        cache: 'npm'
    - run: npm install
    - run: CI=false npm run build
